spring.application.name=bookreaders
spring.config.import=classpath:env.properties

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/bookreaders
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Specify the path of the OpenAPI documentation
springdoc.api-docs.path=/api-docs

springdoc.api-docs.version=OPENAPI_3_1

# Specify the path of the Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# RabbitMq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${application.rabbitmq.username}
spring.rabbitmq.password=${application.rabbitmq.password}

# mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${application.mail.username}
spring.mail.password=${application.mail.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true